name: TimePlayed
version: '1.0-SNAPSHOT'
main: org.queercraft.timePlayed.TimePlayed
api-version: '1.21'
load: POSTWORLD
depend: [Plan]
softdepend: [Plan]
commands:
  timeplayed:
    description: Main command
    usage: /<command> reload
    aliases: []
  playtime:
    description: Shows a player's playtime for today as well as the last 7 and 30 days
    usage: /playtime <player>
    aliases: [pt]
  joindate:
    description: Shows the date a player joined the server for the first time
    usage: /joindate <player>
    aliases: [jd]
  realnameoffline:
    description: Attempts to fetch the username corresponding to a nickname even if the player is offline. If the nickname exists more than once, the result can be inaccurate
    usage: /realnameoffline <player>
    aliases: [rno]
permissions:
  timeplayed.reload:
    description: Allows reloading of the config
    default: op
  timeplayed.generatereport:
    description: Allows generating playtime reports
    default: op
